### ISSUE TITLE
Return type for `Just#bind` insufficiently general

### ISSUE THREAD

**Issue by gadtfly** [filib/ribimaybe#17]
_sorry for the terminology, I'm not familiar with the `Contracts` library_

``` ruby
Just(1).bind{|x|
  Nothing.bind{|y|
    rturn(x+y)}}
```

should return `Nothing`.  Instead:

``` ruby
Contract violation for return value: (ContractError)
    Expected: Ribimaybe::Maybe::Just,
    Actual: Ribimaybe::Maybe::Nothing
    Value guarded in: Ribimaybe::Maybe::Just::bind
    With Contract: Proc => Ribimaybe::Maybe::Just
```

**Comment by filib** [comment]
@gadtfly Not quite do notation but I did add some aliases to make things a little terser. Have a look in https://github.com/filib/ribimaybe/issues/23.
